# This file was generated by GoReleaser. DO NOT EDIT.
cask "ramble" do
  version "0.5.11"

  on_macos do
    on_intel do
      sha256 "cd0c95d67ba84c5e6ec807082b3868ce38d8a591dad273ba4991a385d843062e"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Darwin_x86_64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
    on_arm do
      sha256 "41bec4e807c43f49c40ac9044cf188b3741e9abdca7fd7b877fb14370e5afb1a"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Darwin_arm64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cc0102549b99c7c9e12ca1faf1b1bde50dadadc6a17c1675c8f73a8fee58e09"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Linux_x86_64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
    on_arm do
      sha256 "a9c017728c999295c504ce4416bf58e1477524044b06fbcee54b9b03b50db6fe"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Linux_arm64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
  end

  name "ramble"
  desc "CLI for deploying Nomad packs and jobs"
  homepage "https://ramble.openwander.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ramble"

  # No zap stanza required

end
