# This file was generated by GoReleaser. DO NOT EDIT.
cask "ramble" do
  version "0.5.10"

  on_macos do
    on_intel do
      sha256 "1b2484721203eefb9bbeeb67f1513f90a3007c838e972728aa890af6b2aa47b8"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Darwin_x86_64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
    on_arm do
      sha256 "fdc21bbe01887f9c4863c5df17048cc8f02051cc727ec1357c186601b1127f7f"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Darwin_arm64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c13ce48018970c80e11dc62c53ef6821caafb78621c458125d191fa2cb59be77"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Linux_x86_64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
    on_arm do
      sha256 "f0e8b532b5be1570397666c570181c5c5c9b74c99d25b1ef8ff956f2ee6a7994"
      url "https://github.com/open-wander/ramble/releases/download/v#{version}/ramble_Linux_arm64.tar.gz",
        verified: "github.com/open-wander/ramble/"
    end
  end

  name "ramble"
  desc "CLI for deploying Nomad packs and jobs"
  homepage "https://ramble.openwander.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ramble"

  # No zap stanza required

end
