# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramble < Formula
  desc "CLI for deploying Nomad packs and jobs"
  homepage "https://ramble.openwander.org"
  version "0.5.9"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.9/ramble_Darwin_x86_64.tar.gz"
      sha256 "083dc94ec3f4f165b9593432c470fbf07d3b8295769803c3755688d861b91a29"

      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.9/ramble_Darwin_arm64.tar.gz"
      sha256 "2a3c2b808b1ec85b5d747fc0c273e7629bec055abfa9dad096cdc1deac25c6c6"

      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.9/ramble_Linux_x86_64.tar.gz"
      sha256 "4e5f341debde1647c56082c16bd703ab9f4cf1ea3766f1bcd717b5b02fdb6672"
      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.9/ramble_Linux_arm64.tar.gz"
      sha256 "f5c6b2d913f9e73652ed73675adba1ed749268fe5589071182775f6d3c578d5f"
      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ramble --version")
  end
end
