# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramble < Formula
  desc "CLI for deploying Nomad packs and jobs"
  homepage "https://ramble.openwander.org"
  version "0.5.5"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.5/ramble_Darwin_x86_64.tar.gz"
      sha256 "7de6e0b458c675956914c3746fc42359d66fab8063ac6ba74e860a438f9448de"

      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.5/ramble_Darwin_arm64.tar.gz"
      sha256 "65c998aefae65e8a700fe964174c1f05038336690676449dc2dfdeab589a0cfa"

      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.5/ramble_Linux_x86_64.tar.gz"
      sha256 "643aa44ac9c3aef78e911e383ef9add701ab8c15867ac6da187d0942f34bf687"
      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.5/ramble_Linux_arm64.tar.gz"
      sha256 "6a0c7015e8ce8fb1ed7c95e7531621fc85d44ef94dfd11d4474f27674e95fc49"
      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ramble --version")
  end
end
