# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramble < Formula
  desc "CLI for deploying Nomad packs and jobs"
  homepage "https://ramble.openwander.org"
  version "0.5.7"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.7/ramble_Darwin_x86_64.tar.gz"
      sha256 "7ed21fb0c5d5cc54cc65025c8f7285463699223238a116a88311c1c8c1ea25e9"

      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.7/ramble_Darwin_arm64.tar.gz"
      sha256 "5a05c1c94ab8872cf9fee7faaa7510161a7dc6bda8eb90bf76b23ade65c5df0a"

      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.7/ramble_Linux_x86_64.tar.gz"
      sha256 "07d2536a2dd31a964f86c1bbadaa157da847bba9b2f855da919ded61b9bbd521"
      define_method(:install) do
        bin.install "ramble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-wander/ramble/releases/download/v0.5.7/ramble_Linux_arm64.tar.gz"
      sha256 "ae94577e8523a2630fdd0f39ed85109c323b52a4e865e12f5f1f44e457d49d4a"
      define_method(:install) do
        bin.install "ramble"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ramble --version")
  end
end
